### PR TITLE
feat: Adding drag n drop support using beautiful dnd

### PR DESCRIPTION
**Pull request by imshuffling**
Needed to change the `<table>` markup for `<divs>` to get beautiful dnd to work.

### CODE REVIEW

**Comment by mgschoen** [comment]
Hi @imshuffling, thanks for the nice work! Drag and drop looks and feels really nice 👍 One thing though: I tried to run it locally and the layout was quite thrashed for me:

Bildschirmfoto 2021-02-17 um 19 57 34

Also, I'd like to keep the Contentful look & feel with the Forma 36 components. I see your point with the refs not working with Contentful's table components. But maybe we could try [Cards](https://forma-36-react-components.netlify.app/?path=/docs/components-card--default) instead? They don't have to be nested inside other components, so maybe that makes it easier with the Droppable/Draggable components?

And one last point: I have seen you using the term `ingredients` in the code. I'd suggest we switch to `rows` entirely, because the plan is to [generalize this app](https://github.com/mgschoen/contentful-reference-matrix-field-app/issues) so that it can represent anything and not just ingredients.

Nevertheless: Thanks for the contribution! Appreciate it a lot and looking forward to reading what you think :)

**Review by mgschoen — CHANGES_REQUESTED** [review]
See comment above :)

**Comment by imshuffling** [comment]
Ah shoots, forgot to add the css into the commit. I've pushed it up now and changed from using `ingredients` to `rows` and added "cards" from Forma36 as you suggested.

https://user-images.githubusercontent.com/739061/108265662-fa980d00-7160-11eb-9ea3-03a129d98965.mov

**Comment by mgschoen** [comment]
Awesome, looks relly nice!! I'll take a closer look tomorrow

**Review by mgschoen — APPROVED** [review]
Nice one! Cannot see any reason not to merge this :) Again, thanks for the contribution, really appreciate it!

**Comment by mgschoen** [comment]
@imshuffling Oh one thing, would you be fine if I used your screencast for a tweet?

**Comment by imshuffling** [comment]
@mgschoen No problem at all :) - it will be good to see how far we can take this app.

**Pull request merged**
